// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPs4o9efOmEOirF2TXhcXCtV_Vw7Yays',
    appId: '1:568176469116:web:2a6d732e5e737c8b9455f9',
    messagingSenderId: '568176469116',
    projectId: 'my-api-22910',
    authDomain: 'my-api-22910.firebaseapp.com',
    storageBucket: 'my-api-22910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDco9tkVBCGEY6KUg7DGn5FFol9dLT4R6k',
    appId: '1:568176469116:android:2b87969ac5708df39455f9',
    messagingSenderId: '568176469116',
    projectId: 'my-api-22910',
    storageBucket: 'my-api-22910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh24j1TFvPSfjfxsFjZ_PNNk4iU3htAJA',
    appId: '1:568176469116:ios:0b18addfea4292c19455f9',
    messagingSenderId: '568176469116',
    projectId: 'my-api-22910',
    storageBucket: 'my-api-22910.appspot.com',
    iosBundleId: 'com.example.myBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh24j1TFvPSfjfxsFjZ_PNNk4iU3htAJA',
    appId: '1:568176469116:ios:8b8c85b360b52c519455f9',
    messagingSenderId: '568176469116',
    projectId: 'my-api-22910',
    storageBucket: 'my-api-22910.appspot.com',
    iosBundleId: 'com.example.myBud.RunnerTests',
  );
}
